name: Download Logos

on:
  workflow_dispatch:  # 手动触发

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests pillow

    - name: Run logo downloader
      run: |
        python download_logos.py

    - name: Commit downloaded logos
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add img/
        git commit -m "chore: auto download tvg-logo" || echo "No changes to commit"
        git push
